function spiral(input_wp_filename,spacing,outfilename,lonfirst,inwards)
[startlat,startlon,startaltitude,endlat,endlon] = importtwocoords(input_wp_filename);
addpath('utm2lonlat');

[startx,starty,utmzone] = deg2utm(startlat,startlon);
[endx,endy,~] = deg2utm(endlat,endlon);

start1=[startx,starty]';
end1=[endx,endy]';
altitude=startaltitude;
relvec1=end1-start1;
veclength=norm(relvec1);
flatvec=veclength*[1;0];
cangledif=dot(relvec1,flatvec)/(norm(relvec1)*norm(flatvec));
sangledif=sqrt(abs(cangledif^2-1));
rotdiff=[cangledif -sangledif;sangledif cangledif];

turns=veclength/spacing;

th=0:pi/10:2*pi*turns;
relwp=[turns*th.*cos(th);turns*th.*sin(th)]';

for i=1:length(relwp) %rotate back to original frame
    relwp2(i,:)=(rotdiff*(relwp(i,:)'))';
end
for i=1:length(relwp2) %move to correct position
    relwp3(i,:)=start1+relwp2(i,:)';
end

utmz1=utmzone;
for i=1:length(relwp3)
    utmz(i,:)=utmz1;
end
[lat lon]=utm2deg(relwp3(:,1)',relwp3(:,2)',utmz);
relwp4=[lat lon];

if(inwards)
    relwp4=flipud(relwp4);
end



formatstr='%3.16g,%3.16g,%3.16g';
fid_out = fopen(outfilename,'w');
for i=1:length(relwp4)-1
    if lonfirst
        fprintf(fid_out,formatstr,relwp4(i,1),relwp4(i,2),altitude);
    else
        fprintf(fid_out,formatstr,relwp4(i,2),relwp4(i,1),altitude);
    end
    fprintf(fid_out,'\n');
end
if lonfirst
    fprintf(fid_out,formatstr,relwp4(end,1),relwp4(end,2),altitude);
else
    fprintf(fid_out,formatstr,relwp4(end,2),relwp4(end,1),altitude);
end
fclose(fid_out);





function [...
            startlat,startlon,startaltitude,...
            endlat,endlon] = importtwocoords(filename, startRow, endRow)
        %IMPORTFILE Import numeric data from a text file as column vectors.
        %   [LATITUDES,LONGITUDES,ALTITUDES] = IMPORTFILE(FILENAME) Reads data from
        %   text file FILENAME for the default selection.
        %
        %   [LATITUDES,LONGITUDES,ALTITUDES] = IMPORTFILE(FILENAME, STARTROW,
        %   ENDROW) Reads data from rows STARTROW through ENDROW of text file
        %   FILENAME.
        %
        % Example:
        %   [latitudes,longitudes,altitudes] = importfile('zigzag1.txt',2, 4);
        %
        %    See also TEXTSCAN.
        
        % Auto-generated by MATLAB on 2015/05/25 14:37:30
        
        %% Initialize variables.
        delimiter = '\t';
        if nargin<=2
            startRow = 2;
            endRow = inf;
        end
        
        %% Format string for each line of text:
        %   column9: double (%f)
        %	column10: double (%f)
        %   column11: double (%f)
        % For more information, see the TEXTSCAN documentation.
        formatSpec = '%*s%*s%*s%*s%*s%*s%*s%*s%f%f%f%*s%[^\n\r]';
        
        %% Open the text file.
        fileID = fopen(filename,'r');
        
        %% Read columns of data according to format string.
        % This call is based on the structure of the file used to generate this
        % code. If an error occurs for a different file, try regenerating the code
        % from the Import Tool.
        dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
        for block=2:length(startRow)
            frewind(fileID);
            dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
            for col=1:length(dataArray)
                dataArray{col} = [dataArray{col};dataArrayBlock{col}];
            end
        end
        
        %% Close the text file.
        fclose(fileID);
        
        %% Post processing for unimportable data.
        % No unimportable data rules were applied during the import, so no post
        % processing code is included. To generate code which works for
        % unimportable data, select unimportable cells in a file and regenerate the
        % script.
        
        %% Allocate imported array to column variable names
        latitudes = dataArray{:, 1};
        longitudes = dataArray{:, 2};
        altitudes = dataArray{:, 3};
        
        startlat=latitudes(1);
        startlon=longitudes(1);
        endlat=latitudes(2);
        endlon=longitudes(2);
        %densitylat=latitudes(3);
        %densitylon=longitudes(3);
        startaltitude=altitudes(1);
    end
end